graph TB
    subgraph Administrator
        A1(( ))
        A2[Membuka menu Users]
        A3{Memilih aksi}
        A4[Klik Add User]
        A5[Mengisi form user]
        A6[Klik Edit]
        A7[Update data user]
        A8[Klik Delete]
        A9[Klik Reset Password]
        A10[Input password baru]
        A11(( ))
    end
    
    subgraph Sistem
        S1[Menampilkan daftar user]
        S2[Menampilkan form<br/>input user]
        S3[Hash password<br/>dengan Argon2]
        S4[Simpan user<br/>ke database]
        S5[Catat audit log:<br/>user_create]
        S6[Menampilkan form edit]
        S7[Update user<br/>di database]
        S8[Catat audit log:<br/>user_update]
        S9[Hapus user<br/>dari database]
        S10[Catat audit log:<br/>user_delete]
        S11[Menampilkan dialog<br/>reset password]
        S12[Hash password baru]
        S13[Update password<br/>di database]
        S14[Catat audit log:<br/>password_reset]
    end
    
    %% Fase: Browse Users
    A1 --> A2
    A2 --> S1
    S1 --> A3
    
    %% Fase: Add User
    A3 -->|Add| A4
    A4 --> S2
    S2 --> A5
    A5 --> S3
    S3 --> S4
    S4 --> S5
    S5 --> A11
    
    %% Fase: Edit User
    A3 -->|Edit| A6
    A6 --> S6
    S6 --> A7
    A7 --> S7
    S7 --> S8
    S8 --> A11
    
    %% Fase: Delete User
    A3 -->|Delete| A8
    A8 --> S9
    S9 --> S10
    S10 --> A11
    
    %% Fase: Reset Password
    A3 -->|Reset| A9
    A9 --> S11
    S11 --> A10
    A10 --> S12
    S12 --> S13
    S13 --> S14
    S14 --> A11
    
    style A1 fill:#000
    style A11 fill:#000
